title: MJ's GitHub Page
# description will be from tagline of repo
theme: jekyll-theme-minimal
repository: mjung8/mjung8.github.io
# need this for local server to mimic online
github:
        is_user_page: true
        is_project_page: false
